services:
  cpu:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        UID: "${UID:-1000}"
        GID: "${GID:-1000}"
    volumes:
      - ${HOME}:/workspace
    working_dir: /workspace
    restart: always
    environment:
      - DISPLAY=${DISPLAY}
    network_mode: "host"
    tty: true
    stdin_open: true

  gpu:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        UID: "${UID:-1000}"
        GID: "${GID:-1000}"
        BASE_IMAGE: "nvidia/cuda:12.6.3-cudnn-devel-ubuntu24.04"
        REQ_FILE: "requirements_gpu.txt"
    volumes:
      - ${HOME}:/workspace
    working_dir: /workspace
    environment:
      - DISPLAY=${DISPLAY}
    network_mode: "host"
    tty: true
    stdin_open: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [ gpu ]
